### ISSUE TITLE
yolov8训练速度问题

### ISSUE THREAD

**Issue by qbhnkkk** [CV-ZhangXin/AKConv#5]
您好，我使用库中的代码去训练我自己的Yolov8数据集，但是发现训练的时间比baseline的yolov8慢很多，并且显存占用更多，不知道您在训练的时候是否有遇到这个问题？

**Comment by CV-ZhangXin** [comment]
@qbhnkkk ，留下一个联系方式吧，看我能不能帮助你。

**Comment by qbhnkkk** [comment]
@CV-ZhangXin 好的！qq:1030634559，谢谢了！

**Comment by niani3146** [comment]
我也出现这个问题，请问解决了吗？
